jobs:
  include:
  - stage: Build

    language: node_js
    sudo: required
    services:
    - docker
    node_js: 8
    script: |
      npm run build &&
      docker build -t ${DOCKER_USER}/genie-logiciel .
    after_success: |
      if [ "${TRAVIS_BRANCH}" == "master" ]; then
        echo $(DOCKER_PASS) | docker login -u $(DOCKER_USER) --password-stdin && docker push ${DOCKER_USER}/genie-logiciel
      fi

  - stage: Build

    language: go
    go: '1.10'
    after_success: |
      bash <(curl -s https://codecov.io/bash)

      if [ "${TRAVIS_BRANCH}" == "master" ]; then
        ./concat_doc.sh
        ./bin/algolia -source ./dist/doc/genie.md -app "${ALGOLIA_APP}" -key "${ALGOLIA_KEY}" -index "${ALGOLIA_INDEX}"

        curl -s -X POST https://goreportcard.com/checks?repo=github.com/ViBiOh/httputils
      fi

  - stage: Deploy

    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script: "curl -H 'Authorization: GitHub ${GITHUB_OAUTH_TOKEN}' -X POST https://dashboard-api.vibioh.fr/containers/cours/ --data-binary @docker-compose.yml"

stages:
  - Build
  - name: Deploy
    if: branch = master

notifications:
  email: false
