version: '2'

services:
  site:
    image: vibioh/genie-logiciel
    command:
    - -csp
    - default-src 'self'; base-uri 'self'; script-src 'self' 'unsafe-inline' cdn.jsdelivr.net/algoliasearch/3/ cdnjs.cloudflare.com/ajax/libs/rollbar.js/; style-src 'self' 'unsafe-inline'; connect-src 'self' *.algolia.net *.algolianet.com api.rollbar.com
    - -headers
    - X-UA-Compatible:ie=edge~content-language:fr
    - -env
    - ALGOLIA_APP,ALGOLIA_KEY,ALGOLIA_INDEX,ROLLBAR_TOKEN,ENVIRONMENT
    - -tracingName
    - cours
    - -rollbarToken
    - ${ROLLBAR_TOKEN}
    - -rollbarServerRoot
    - github.com/ViBiOh/viws
    - -rollbarEnv
    - prod
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: l3miage.fr, www.l3miage.fr'
      traefik.protocol: 'https'
      traefik.port: '1080'
      traefik.frontend.rateLimit.extractorFunc: 'client.ip'
      traefik.frontend.rateLimit.rateSet.first.period: '60s'
      traefik.frontend.rateLimit.rateSet.first.average: '100'
      traefik.frontend.rateLimit.rateSet.first.burst: '200'
    environment:
      ALGOLIA_APP: ${ALGOLIA_APP}
      ALGOLIA_KEY: ${ALGOLIA_KEY}
      ALGOLIA_INDEX: ${ALGOLIA_INDEX}
      ROLLBAR_TOKEN: ${ROLLBAR_CLIENT_TOKEN}
      ENVIRONMENT: 'prod'
    logging:
      driver: json-file
      options:
        max-size: '10m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 67108864
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik
