version: '2'

services:
  cours:
    image: vibioh/genie-logiciel
    command: -domain '*.google-analytics.com fonts.googleapis.com fonts.gstatic.com'
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: cours.${DOMAIN}'
      traefik.port: '1080'
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 134217728
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik
