version: '2'

services:
  cours:
    image: vibioh/genie-logiciel
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: cours.${DOMAIN}'
      traefik.port: '1080'
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: 'no'
    read_only: true

networks:
  default:
    external:
      name: swarm-net