version: '2'

services:
  site:
    image: vibioh/l3miage
    command:
    - -csp
    - default-src 'self'; base-uri 'self'; script-src 'self' 'unsafe-inline' cdn.jsdelivr.net/algoliasearch/3/; style-src 'self' 'unsafe-inline'; connect-src 'self' *.algolia.net *.algolianet.com; child-src www.youtube.com
    - -headers
    - X-UA-Compatible:ie=edge~content-language:fr
    - -env
    - ALGOLIA_APP,ALGOLIA_KEY,ALGOLIA_INDEX
    labels:
      traefik.http.routers.l3miage-http.rule: Host(`l3miage.fr`) || Host(`www.l3miage.fr`)
      traefik.http.routers.l3miage-http.entrypoints: http
      traefik.http.routers.l3miage-http.middlewares: redirect@file
      traefik.http.routers.l3miage-https.rule: Host(`l3miage.fr`) || Host(`www.l3miage.fr`)
      traefik.http.routers.l3miage-https.entrypoints: https
      traefik.http.routers.l3miage-https.middlewares: compress@file
      traefik.http.routers.l3miage-https.tls: true
      traefik.http.routers.l3miage-https.tls.certResolver: default
      traefik.http.services.l3miage-service.loadbalancer.passhostheader: true
      traefik.http.services.l3miage-service.loadbalancer.server.port: '1080'
      traefik.http.middlewares.l3miage-rate-limit.ratelimit.average: '10'
      traefik.http.middlewares.l3miage-rate-limit.ratelimit.burst: '50'
    environment:
      ALGOLIA_APP: ${ALGOLIA_APP}
      ALGOLIA_KEY: ${ALGOLIA_KEY}
      ALGOLIA_INDEX: ${ALGOLIA_INDEX}
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 67108864
    security_opt:
    - no-new-privileges
