apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: l3miage
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.39"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: flux-system
      interval: 120m
  values:
    nameOverride: l3miage
    image:
      repository: vibioh/l3miage:latest # {"$imagepolicy": "default:l3miage"}
    init:
      enabled: true
      repository: vibioh/l3miage:latest # {"$imagepolicy": "default:l3miage"}
      env:
        REVEALGOLIA_LOGGER_JSON: true
      secrets:
        REVEALGOLIA_APP: AgDH2XVHHZ4jgTT7NbYULUW5VzaJzqb4ypKudmpBEyViZLq4uPx9IWyvBmk+yBnJghFkaEDb5YLTOvDh/pIT+WdlZQwEvUF4hUsmUf9RAw06Y7UXcZFUVVywwLmpvHp32kf3mb2cbbkNDsxBDid99EafWGmflyNIrPbpvi6zgr5aCQgbn/3Xw7PmSee6T58MVwqWxb4m8rksLIrXuJVDxaTrT1MiofIx4dSQWoRuaJdJ1dEnc8aLu/dPUqISQReSpNfN2OCIqNIpqqJqpscpdM8pmYo+DrpGiK+Q5onQgaGWz4w2KwX+fTXi1Z/Y7KdKFjSujbV224IeieVZmIDL/mIDlTLYblEPKLLhevRzEcGBIf0U/7uxh1d9Hv2YMkGB6g7GEcqXyC48dBEXsT4tz15RTtl/vdYORIYPWOko72LJoniMhHjmKLzf/eyRrWNMhV4vCt4SAHJR+vI3NSurEOJ1M0x+GPpXp8kimkz38O/P77i6Q+aCceMx4AF9LCzZw7JfmOvBtm1x9KGz1prgPwGISYTH84tztzC6Dr2vziRgMeaxONw8DdHmDj/JAQhqh/dSgwZvMO1WeKoz68YshNFu4dAD75noyj4+BCFTo80CyQLgGUdyziKX3UE7YaAm2pCYlavrP8f99XUrAw68QoJzPCLbKt7MopW6Bdl+pgfyIppVydqjFNZOj9XmAGjTwA9NlVz0YCTWkqGd
        REVEALGOLIA_INDEX: AgANoiPAdI7ApGMV4p3xiy5vNN/BlaHs4dZ3CuMo+/Z4TIDU5yQ7PZiaiQ6a2S5t5c6BHmDWNC4doazJtuvWyTjGddgpdXOWtfJEguowaQX5QfvIjXp4zyGoe3BF1jgrexJKBhtAaydrcfUgBYAcU9dTdc+zxyXKJTzAZElnnDQM32rQ9B9sMUqd/UqQ0a8dep4DLZdpmZKmoXbIOxxysqgaHF662zXAZAhGLSe2c2cVKjAE6Z4ztKjE591d7GusnVKu6QZwPtGJO7ALJwWy4T2SMgcxJKuNiZ0d7j3p2hlxrnCjsq9IYiFoH6qER7knyGRDif/etneeajHF7jx870C1RIsCHOPuSv2tTb6xCiWE7bC3ceILCOrhwBsxEIsSddIG65s6K7l2sZqz3/7dGakmcwh33z2k2/kgQi9Jn6wPfT41cgxcw2sLn8zo16ng1gyx/p+sy/oCcbkIukxpwDfEinfriXi9Vq0ZKHcLGmIWX6jxx/x14LQtEOTZYRVQYx5rGOyBLVwPXMKkAVOsXZFdSVw0/65E+426SRihGsXW9fiUyMEp1PgC1+T525GgkMZlRkMwxN3oWw8grSC+fyWcg1oryS0TV2GlOwuOAEMPo9othCVGq2EotkEPD0HBXOqeTx/35sYgT0CkE7vOkD5jxIOddMssYQpEXMs8WuGoNqURpH0t1vRdiX0RpV9vMKIanKHBHsGv
        REVEALGOLIA_KEY: AgBmHk3SToOSppt7Bu5J1E5MXcTk2lgowWDlL+XWmCqLQqq8LKhmwNV307rAVibzRUQL099gV9NDbcPtHa0Rb9cgHPi7BNHlvyVZZseho9k+Ubwy149q0bBUcjPxQqOGdAS7zNeWM06wypIvPjVPZfY8hiVUKM8Jgtm2+OKQns43fa1KFwGj5dpPpbtH23UhXb9qr3g1CXD6/bUANJaE92Zz/gB4HlGdFkjmKLc7nkJGwOMbmbzTLpqxYVO/lhjaW0JJqDDLP8oPYo45ra7c/U+mB7/La8et3jOVKumx6/jDqRBbgzTV+mAAuTfDLR/+5oJR4t3d5ZJdrc4VeCoD3eQQZaXR0d5R0p60qtoo3mHYZJ6MkNRff31CuWIK+omNIbv6WAluU8QHNLjlKDbXVfh1acT8G/3IT5bShlJdCnCo6h/UyK4gf6BgVaXgr1AnTiMhavP9wdlQ2g9q4SrOaE6pzu16pmbG555JaIrMd41cykt0l5Na4YpwAaanpVXZAZ6MG/nwcsJh6GEV1sFKOJLuVJ9uAWlDPwxnBhh0rV9pUGC0Q1nYmakFopXQ8a/52GS/b63XBoTBsuH8Jv/2AtkwIQpZ5JmavkuXy+20mOEoboHI7vfHw4WJ87AFzuFZG+WnnGxJHHJlOvRuSG8aqL4Gqaz4RLoyKKWfdws20+HjHBBemKGIRk6Yskx+KTMo+CrHkfbQCFTjf75tUINwSAAL0DVGKen7kNjgCrPltNN9yg==
      command:
      - /revealgolia
      - -source
      - /www/doc/genie.md
    config:
      VIWS_LOGGER_JSON: "true"
    secrets:
      ALGOLIA_APP: AgB4gklcq6+FkUaGIp/Mlj6e+JMYnsmqJDiGuwfFm51+MlMTD5ZarMa/GQRIFHMxqmKpmHGDrh9l3iMvJozOFZUaxa9jbu9X2cXVNec/wcbwoLZSgQEefubYzbloouJfvzezDSSUCZH4ws4hlhUowzoEQrvkwaE1n//rsv7M2ZxpgTAZdrWR7kyJC6dXk6m/mHK5POJzEJus7HkDG03u6ioTF8jZTewNFxfme4CfUYB4fuij7gfvrkh56ZWW27wZrufE+x2pa+Ie8HROcRKeUb9nKWRfIFvMVrE0pWMzYADOA8PDIaGao7o+7CLQoGhOwX1gu2BauT/c47eUrotGp9wk0BOI5EvdW80NhT8sWkbfnE8ubUBoIwqjyb/PBWhpMfasGcrbHBrAlfMTz8kR1KmPE0u9Y4XJ0I9oEEEZlFB8fJRPzuzATs10RmIGX1ZonG5MTVUtUe+ZfcdymQEOprZGG4kNpDUTYtsJqVi9zueHl/h1rKgkMXNh8/OVwx/EftVoK35B01s6eu1bM3dBG5zdIM+5I8AJM5YGCb44bl1pzoxBDMSkY/Pj5d0GcB9AE7D4K76Is8t7cgkp63RQYNyTBEs1dQ4ITYUtuOolAsxKoJ4MPTZDSHRIrlHRiHGZSaem8BiuOKBI/W6Oh7BU93Ftve2dKunJMD3aPBPNZUyFScxNWUxEEyok7RXJT7zWpl79a0ibwIbd/k5q
      ALGOLIA_INDEX: AgAbYKp9SIqr1TQZ6sC/5lTbE10dKR3L1py9Pa4aNxD4hZqdDYGqellyeldTunQNciAtaPk6jzq4DvULssyoihgiUc63/50I8GnYgIyjPdVfvXSHmDLJoSNZ0W1r8hYYoGsgW8AKRNgTn2nvLtyYfcap+7pjP0/pRvvfzjSQfwgqx13rKdEaTW9d755O/dyagViqW5cSxOxihJxhYPhsELYs2ROHzbqp+kYcFeRNdWZOJI5RXeK8DZRzJ/tQq6Tgj4dORbL/poEZ1sAZYfmbv9H173pLrpulB7QLjZcSVHv5E3w0i82hDjwQAOLnG1pv49cwwkOcDzJV2Y1Rt43zmebpmOBbjT61Urr0pnSMurnqGXV6KAFC1mnhN6p3tpRGK79jxtr0qrkOK+UmdiMs8clokBITAIvpqCisdmyFDG6UyYQtoePKYiAx9Pof3DuJlk8HJ4AS7s5tvvmpknQMWo95Whf6Z7RLF47tI4lTK0XopUOuv6jG69lmy+XGGCOZnLbDjqXMhy6cQOfEYffoPP+hLMB7AloRazWTOzreqAigXh7wxdDv3QvMzjkKK/N8eYWefwsBj18tNaoUKNegGepC4NG3jSmdVXtbTT1D0SZoqWVQQRB2KtguNcH7ggMZfFFxJWJ9iPctJxjbLW/LplWqEvMDC1OHPaBuhY93e3XOj3ldod4N1nowJoFC3eKjfwCX0hIQnLxT
      ALGOLIA_KEY: AgCQGIiujRWmt/JeacLFZ/V2kXoFbFnTnLdaV0f71zx/QfsHjqT/VTBFVCuUcOaAyM/I/ABjYSJDnwYXbdkV4paRoBAdtDtEhDqpElzLZURiFDqbSsSSWmkYDqMG34kIetqjTaGubpk9h8VPnsuydmirtBbd/g2hgcFHbmSrgnyYWxFd8qu8R8pyHSgDpq5b9Vc5WPxShi8Y86loZY/Nx7lKoVSz7wcHf04axp3nCAPn/eGQ8oEUrq1uZgX0gFnM/HUsv/GXCLOgVGZVhi5Yo965Cf+vyVj+hCbmBn8tIkR/OVetpUSdRyn3iAHAh/Ww//Hfg+HITnBffc9BU9POFxK8U8b9YVVD6yM4t054YlNdJuQ30Rczkpdia6K5JDVO5EOi4ChbFV/c+wAIEaeVt/U2Fcp+7i6nqCfSz/yfr3zHQL6Yfs+vPsSFg6vx8euZGUoGJMQjVtUMv3xKLVqJ4i2yh4roI/yT4HhD/9DPAXTHdHdZnIBYq49sXK4hv3qFkm1QyZQRJ2Kx5ajhJmtgEqjIz0+fLFps9EP7nAWwf/5PIM0E8sDvB9WKlQCnfFZNnFFTCM23dfF29XGURv02RzZs9wRXTuUcp/rwrtsE2qtCDw9rOfCQ/owD2p1lVZcVlhuPGRZkz8/bNu26XEWTlstKaVAClFXux/Bci5zWMMVJd09FD1cHS5WB/exN44+R6kTPB44yyrZL65pJ219X0eAp7J48WKsrRH6lBEAg3JRbiA==
    ingress:
      enabled: true
      hosts:
      - l3miage.fr
      - www.l3miage.fr
      - genie.l3miage.fr
      redirect:
        regex: ^https?://(?:www|genie).l3miage.fr(.*)
        replacement: https://l3miage.fr${1}
