# https://dependabot.com/docs/config-file/

version: 1
update_configs:
- package_manager: "javascript"
  directory: "/"
  update_schedule: "weekly"
  default_reviewers:
  - "ViBiOh"
  default_assignees:
  - "ViBiOh"
  automerged_updates:
  - match:
      dependency_type: "all"
      update_type: "all"
- package_manager: "javascript"
  directory: "/sample/tdd/"
  update_schedule: "weekly"
  default_reviewers:
  - "ViBiOh"
  default_assignees:
  - "ViBiOh"
  automerged_updates:
  - match:
      dependency_type: "all"
      update_type: "all"
- package_manager: "java:maven"
  directory: "/sample/java/"
  update_schedule: "weekly"
  default_reviewers:
  - "ViBiOh"
  default_assignees:
  - "ViBiOh"
  automerged_updates:
  - match:
      dependency_type: "all"
      update_type: "all"
